### ISSUE TITLE
ValueError: Cannot reset context for Parameter 'fcn2_resnetv1s_conv0_weight' because it has not been initialized.

### ISSUE THREAD

**Issue by kind50ul** [postor/train-aeroscapes-with-gluon#1]
Hey,
I've tried running this code but after copying the Segmentation folder into the ImageSets folder I'm getting this error

ValueError                                Traceback (most recent call last)
<ipython-input-6-b4a16acf4e07> in <module>
     15 if __name__ == "__main__":
     16     args = parse_args()
---> 17     trainer = Trainer(args)
     18     if args.eval:
     19         print('Evaluating model: ', args.resume)

<ipython-input-5-f65e1a10ecae> in __init__(self, args)
     34         print(model)
     35         self.net = DataParallelModel(model, args.ctx, args.syncbn)
---> 36         self.evaluator = DataParallelModel(SegEvalModel(model), args.ctx)
     37         # resume checkpoint if needed
     38         if args.resume is not None:

~/anaconda3/lib/python3.7/site-packages/gluoncv/utils/parallel.py in __init__(self, module, ctx_list, sync)
    168 
    169     def __init__(self, module, ctx_list=None, sync=False):
--> 170         module.collect_params().reset_ctx(ctx=ctx_list)
    171         self.ctx_list = ctx_list
    172         self.module = module

~/anaconda3/lib/python3.7/site-packages/mxnet/gluon/parameter.py in reset_ctx(self, ctx)
    877         """
    878         for i in self.values():
--> 879             i.reset_ctx(ctx)
    880 
    881     def setattr(self, name, value):

~/anaconda3/lib/python3.7/site-packages/mxnet/gluon/parameter.py in reset_ctx(self, ctx)
    462         else:
    463             raise ValueError("Cannot reset context for Parameter '%s' because it "
--> 464                              "has not been initialized."%self.name)
    465 
    466 

ValueError: Cannot reset context for Parameter 'fcn2_resnetv1s_conv0_weight' because it has not been initialized.

Please tell me which version of mxnet and gluoncv you used for this project

Thank you.

**Comment by postor** [comment]
I was not using anaconda, I wonder if it's cause
mine pure python + cuda on ubuntu 18.04

Python 3.6.8
CUDA 10.1
mxnet-cu101==1.5.1.post0
gluoncv==0.5.0

can you run other gluon examples on gluon official site?

**Comment by kind50ul** [comment]
Yes, I can run the other gluon examples but not this.
Can you send me your complete repo which is ready to run? Or update your repo?

**Comment by postor** [comment]
this repo is enough for training as you can see in my video capture https://www.youtube.com/watch?v=yYhGy2Akg2o&list=PLM1v95K5B1ntVsYvNJIxgRPppngrO_X4s, so if you can run other examples, it should work, for there is only tiny change in my code, as you can compare them 

https://github.com/postor/train-aeroscapes-with-gluon/blob/master/train_fcn.py
vs
https://gluon-cv.mxnet.io/_downloads/1f67ebbf3e0adc5c6fa863a3bc7672a6/train.py
you can find it here https://gluon-cv.mxnet.io/build/examples_segmentation/train_fcn.html#

if you can run this official code, try use official code ,and merge the diffs step by step, and see where errors, if the official code fails, raise an issue to gluon official

![image](https://user-images.githubusercontent.com/699002/72196566-1906e180-3454-11ea-97b5-b50cb019c340.png)
![image](https://user-images.githubusercontent.com/699002/72196584-3c319100-3454-11ea-95dc-f5679345b41c.png)

**Comment by postor** [comment]
if you still have problem,  try reopen this issue or email to me

**Comment by gvteja99** [comment]
So I solved the issue by install mxnet for cuda 10.0 by using the command 
`pip install mxnet-cu100mkl`
and after that I ran into a cuda malloc error, but it ran after i took batch-size=1.

Thanks for the code.

**Comment by postor** [comment]
@gvteja99 really good gpu needed , I tried on GTX1070m failed, then switched to gtx2080ti worked
